# Check on http://lint.travis-ci.org/ after modifying it!
sudo: false
os:
  - linux
  # - osx
language: python
python:
  - "3.4"
  - "3.5"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels https://conda.anaconda.org/biocore
  # Update conda itself
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
install:
  - conda create -n test_env python=$TRAVIS_PYTHON_VERSION --file ci/conda_requirements.txt
  - source activate test_env
  - pip install -r ci/pip_requirements.txt
  - pip install . --no-deps
script:
  - WITH_COVERAGE=TRUE make test
after_success:
  - coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/730436c08fd7f89462b0
    on_success: change
    on_failure: always
